import Vue from 'vue'
import { Tabbar, TabbarItem, NavBar, Form, Field, Button, Toast, Image as VanImage, Grid, GridItem, Icon, List, Cell, CellGroup, Tag, IndexBar, IndexAnchor, Swipe, SwipeItem, Lazyload, Search, Col, Row, Area, DropdownMenu, DropdownItem, Picker, Popup, Uploader } from 'vant'

Vue.use(Uploader)

Vue.use(Popup)

Vue.use(Picker)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Area)
Vue.use(Col)
Vue.use(Row)
Vue.use(Search)
Vue.use(Lazyload)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(IndexBar)
Vue.use(IndexAnchor)
Vue.use(Tag)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(List)
Vue.use(Icon)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(VanImage)
Vue.use(Toast)
Vue.use(Button)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Form)
Vue.use(Field)
